import 'package:firl/app/design_system/foundations/colors/app_colors.dart';
import 'package:flutter/material.dart';

final lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: AppColors.brand.primary.normal,
  onPrimary: AppColors.neutrals.white.light,
  primaryContainer: const Color(0xFFE2DFFF),
  onPrimaryContainer: const Color(0xFF0F0069),
  secondary: const Color(0xFF5E5C71),
  onSecondary: const Color(0xFFFFFFFF),
  secondaryContainer: const Color(0xFFE3E0F9),
  onSecondaryContainer: const Color(0xFF1A1A2C),
  tertiary: const Color(0xFF7A5368),
  onTertiary: const Color(0xFFFFFFFF),
  tertiaryContainer: const Color(0xFFFFD8EA),
  onTertiaryContainer: const Color(0xFF2F1123),
  error: const Color(0xFFBA1A1A),
  onError: const Color(0xFFFFFFFF),
  errorContainer: const Color(0xFFFFDAD6),
  onErrorContainer: const Color(0xFF410002),
  outline: const Color(0xFF787680),
  background: const Color(0xFFFFFBFF),
  onBackground: const Color(0xFF1C1B1F),
  surface: const Color(0xFFF7F7FC),
  onSurface: const Color(0xFFADB5BD),
  surfaceVariant: const Color(0xFFE4E1EC),
  onSurfaceVariant: const Color(0xFF47464F),
  inverseSurface: const Color(0xFF313034),
  onInverseSurface: const Color(0xFFF3EFF4),
  inversePrimary: const Color(0xFFC3C0FF),
  shadow: const Color(0xFF000000),
  surfaceTint: const Color(0xFF4836FF),
  outlineVariant: const Color(0xFFC8C5D0),
  scrim: const Color(0xFF000000),
);

const darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFF375FFF),
  onPrimary: Color(0xFFF7F7FC),
  primaryContainer: Color(0xFF2D00E6),
  onPrimaryContainer: Color(0xFFE2DFFF),
  secondary: Color(0xFFC7C4DD),
  onSecondary: Color(0xFF2F2E42),
  secondaryContainer: Color(0xFF464559),
  onSecondaryContainer: Color(0xFFE3E0F9),
  tertiary: Color(0xFFEAB9D1),
  onTertiary: Color(0xFF472639),
  tertiaryContainer: Color(0xFF603C50),
  onTertiaryContainer: Color(0xFFFFD8EA),
  error: Color(0xFFFFB4AB),
  onError: Color(0xFF690005),
  errorContainer: Color(0xFF93000A),
  onErrorContainer: Color(0xFFFFDAD6),
  outline: Color(0xFF928F9A),
  background: Color(0xFF0F1828),
  onBackground: Color(0xFFF7F7FC),
  surface: Color(0xFF152033),
  onSurface: Color(0xFFADB5BD),
  surfaceVariant: Color(0xFF47464F),
  onSurfaceVariant: Color(0xFFC8C5D0),
  inverseSurface: Color(0xFFE5E1E6),
  onInverseSurface: Color(0xFF1C1B1F),
  inversePrimary: Color(0xFF4836FF),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFFC3C0FF),
  outlineVariant: Color(0xFF47464F),
  scrim: Color(0xFF000000),
);
